# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Offense count: 153
Metrics/AbcSize:
  Max: 302

# Offense count: 32
Metrics/BlockNesting:
  Max: 8

# Offense count: 29
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1051

# Offense count: 88
Metrics/CyclomaticComplexity:
  Max: 57

# Offense count: 432
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 204

# Offense count: 201
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 431

# Offense count: 89
Metrics/PerceivedComplexity:
  Max: 63

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AccessModifierIndentation:
  Enabled: false

# Offense count: 85
Style/Documentation:
  Enabled: false

# Offense count: 6
# Configuration parameters: Exclude.
Style/FileName:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: false

# Offense count: 179
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: false

# Offense count: 117
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

# Offense count: 19
Style/MultilineTernaryOperator:
  Enabled: false

# Offense count: 71
# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/NegatedWhile:
  Enabled: false

# Offense count: 2
Style/NestedTernaryOperator:
  Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 104
# Cop supports --auto-correct.
Style/NilComparison:
  Enabled: false

# Offense count: 69
# Cop supports --auto-correct.
# Configuration parameters: IncludeSemanticChanges.
Style/NonNilCheck:
  Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 10

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: false

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Offense count: 22
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/VariableName:
  Enabled: false
